matchBlocks=archisnap:concrete_barex
method=ctm
tiles=concrete_barex00 concrete_barex01 concrete_barex02 concrete_barex03 \
      concrete_barex26 concrete_barex26 concrete_barex26 concrete_barex26 \
      concrete_barex26 concrete_barex26 concrete_barex26 concrete_barex26 \
      concrete_barex12 concrete_barex13 concrete_barex14 concrete_barex15 \
      concrete_barex26 concrete_barex26 concrete_barex26 concrete_barex26 \
      concrete_barex26 concrete_barex26 concrete_barex26 concrete_barex26 \
      concrete_barex24 concrete_barex25 concrete_barex26 concrete_barex27 \
      concrete_barex26 concrete_barex26 concrete_barex26 concrete_barex26 \
      concrete_barex26 concrete_barex26 concrete_barex26 concrete_barex26 \
      concrete_barex36 concrete_barex37 concrete_barex38 concrete_barex39 \
      concrete_barex26 concrete_barex26 concrete_barex26 concrete_barex26 \
      concrete_barex26 concrete_barex26 concrete_barex26
