matchBlocks=archisnap:concrete_bare
method=ctm
tiles=concrete_bare00 concrete_bare01 concrete_bare02 concrete_bare03 \
      concrete_bare26 concrete_bare26 concrete_bare26 concrete_bare26 \
      concrete_bare26 concrete_bare26 concrete_bare26 concrete_bare26 \
      concrete_bare12 concrete_bare13 concrete_bare14 concrete_bare15 \
      concrete_bare26 concrete_bare26 concrete_bare26 concrete_bare26 \
      concrete_bare26 concrete_bare26 concrete_bare26 concrete_bare26 \
      concrete_bare24 concrete_bare25 concrete_bare26 concrete_bare27 \
      concrete_bare26 concrete_bare26 concrete_bare26 concrete_bare26 \
      concrete_bare26 concrete_bare26 concrete_bare26 concrete_bare26 \
      concrete_bare36 concrete_bare37 concrete_bare38 concrete_bare39 \
      concrete_bare26 concrete_bare26 concrete_bare26 concrete_bare26 \
      concrete_bare26 concrete_bare26 concrete_bare26
